services:
  - type: web
    name: nepse-api
    env: python
    runtime: python-3.10.0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn nepse_api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
